name: Terraform Multi-Environment Deploy

on:
  push:
    branches:
      - modular-project

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Select Environment Folder
        run: |
          if [[ "${GITHUB_REF##*/}" == "modular-project" ]]; then
            echo "ENV_DIR=envs/dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "ENV_DIR=envs/prod" >> $GITHUB_ENV
          fi

      - name: Terraform Init
        working-directory: ${{ env.ENV_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.ENV_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.ENV_DIR }}
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/modular-project' || github.ref == 'refs/heads/main'
        working-directory: ${{ env.ENV_DIR }}
        run: terraform apply -auto-approve